version: "3"
services:
  app:
    image: kingmant/ifmeorg
    build:
      context: .
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
    volumes:
      - node_cache:/app/client/node_modules
      - bundle_cache:/bundle
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - db
    command: /bin/sh -c "rake db:create && rake db:migrate && bundle exec foreman start -f Procfile.dev"


  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  bundle_cache:
  postgres_volume:
  node_cache:
